-- insert into designations(id,created_on, name, updated_on) values (1,now(),'software developer',now());
-- insert into designations(id,created_on, name, updated_on) values (2,now(),'Software engineer',now());
-- insert into designations(id,created_on, name, updated_on) values (3,now(),'DevOps Engineer',now());
-- insert into designations(id,created_on, name, updated_on) values (4,now(),'Ux/Ui designer',now());